name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  ubuntu-build:
    name: Build - Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install apt package
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen

    - name: Install pip packages
      run: pip install -r third_party/requirements.txt

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DDEVELOPER_MODE=ON -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TESTS=ON

    - name: Generate source from spec, check for uncommitted diff
      run: cmake --build ${{github.workspace}}/build --target check-generated

    - name: Build
      run: cmake --build ${{github.workspace}}/build

  windows-build:
    name: Build - Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install prerequisites
        run: python3 -m pip install -r third_party/requirements.txt

      - name: Configure CMake
        run: cmake -DCMAKE_POLICY_DEFAULT_CMP0094=NEW -DDEVELOPER_MODE=ON -DBUILD_TESTS=ON -B ${{github.workspace}}/build

      - name: Generate source from spec, check for uncommitted diff
        run: cmake --build ${{github.workspace}}/build --target check-generated --config ${{env.BUILD_TYPE}}

      - name: Build all
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
