name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  ubuntu-build:
    name: Build - Ubuntu
    strategy:
      matrix:
        config:
          - {os: 'ubuntu-20.04', compiler: {c: gcc, cxx: g++}}
          - {os: 'ubuntu-22.04', compiler: {c: gcc, cxx: g++}}
          - {os: 'ubuntu-22.04', compiler: {c: clang, cxx: clang++}}
    runs-on: ${{matrix.config.os}}

    steps:
    - uses: actions/checkout@v3

    - name: Install apt packages
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen ${{matrix.compiler.c}}

    - name: Install pip packages
      run: pip install -r third_party/requirements.txt

    - name: Configure CMake
      run: >
        cmake
        -B${{github.workspace}}/build
        -DCMAKE_C_COMPILER=${{matrix.config.compiler.c}}
        -DCMAKE_CXX_COMPILER=${{matrix.config.compiler.cxx}}
        -DUR_ENABLE_TRACING=ON
        -DUR_DEVELOPER_MODE=ON
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DUR_BUILD_TESTS=ON
        -DUR_FORMAT_CPP_STYLE=ON

    - name: Generate source from spec, check for uncommitted diff
      if: matrix.config.os == 'ubuntu-22.04'
      run: cmake --build ${{github.workspace}}/build --target check-generated

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure -L "python|uma|loader|validation|tracing|unit|urtrace"

  windows-build:
    name: Build - Windows
    strategy:
      matrix:
        config:
          - {os: 'windows-2019'}
          - {os: 'windows-2022'}
    runs-on: ${{matrix.config.os}}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install prerequisites
      run: python3 -m pip install -r third_party/requirements.txt

    - name: Configure CMake
      run: >
        cmake
        -B${{github.workspace}}/build
        -DCMAKE_POLICY_DEFAULT_CMP0094=NEW
        -DUR_ENABLE_TRACING=ON
        -DUR_DEVELOPER_MODE=ON
        -DUR_BUILD_TESTS=ON
        -DUR_FORMAT_CPP_STYLE=ON

    - name: Generate source from spec, check for uncommitted diff
      if: matrix.config.os == 'windows-2022'
      run: cmake --build ${{github.workspace}}/build --target check-generated --config ${{env.BUILD_TYPE}}

    - name: Build all
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure -L "python|uma|loader|validation|tracing|unit|urtrace"
